---
- name: Retrieve setup playbooks
  hosts: localhost
  become: true

  tasks:
    - name: Create a directory if it does not exist
      ansible.builtin.file:
         path: /home/vagrant/Documents/playbooks
         state: directory
         mode: '0755'


    - name: Retrieve setup playbooks
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/carinam17/linux-exercises/main/{{ item }}
        dest: /home/vagrant/Documents/playbooks
        mode: 0644
      loop:
       - setup1.yml
       - setup2.yml  
