---
- name: Retrieve files for exercises
  hosts: localhost
  become: true

  tasks:
    - name: Retrieve script templates
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/carinam17/linux-exercises/main/{{ item }}
        dest: /home/vagrant/script-templates
        mode: 0644
        owner: vagrant
        user: vagrant
      loop:
       - make-directory-template.sh
       - copy-file-template.sh  
