---
- name: Retrieve setup playbooks
  hosts: localhost
  become: true

  tasks:
    - name: Create a directory if it does not exist
      ansible.builtin.file:
         path: /home/vagrant/script-templates
         state: directory
         mode: '0775'
         user: vagrant
         group: vagrant


    - name: Retrieve shell scripts
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/carinam17/linux-exercises/main/copy-file-template.sh
        dest: /home/vagrant/script-templates
        mode: 0664
        user: vagrant
        group: vagrant


    - name: Retrieve shell scripts
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/carinam17/linux-exercises/main/create-file-template.sh
        dest: /home/vagrant/script-templates
        mode: 0664
        user: vagrant
        group: vagrant
