---
- name: Retrieve setup playbooks
  hosts: localhost

  tasks:
    - name: Create a directory if it does not exist
      ansible.builtin.file:
         path: /home/vagrant/{{ item }}
         state: directory
         mode: '0775'
      loop:
         - script-templates
         - text-files
         

    - name: Retrieve script templates
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/carinam17/linux-exercises/main/{{ item }}
        dest: /home/vagrant/scripts-templates
        mode: 0666
      loop:
       - remove-file-template.sh
       - copy-file-template.sh
       - rename-file-template.sh
       - make-directory-template.sh
       
