---
- name: Create directories
  hosts: localhost
  become: true

  tasks:
    - name: Create a directory if it does not exist
      ansible.builtin.file:
         path: /home/vagrant/{{ item }}
         state: directory
         mode: '0775'
         user: vagrant
         group: vagrant
      loop:
         - playbooks
         - script-templates
         - text-files
