---
- name: Remove users contained in a list
  hosts: localhost
  become: true
  vars:
    users:
      - "user1"
      - "user2"
      - "user3"

  tasks:
     - name: Remove users
       user:
         name: "{{ item }}"
         state: absent
         remove: yes
       loop: "{{ users }}"
